package pojo;
// Generated Oct 12, 2022 10:33:49 PM by Hibernate Tools 4.3.1


import DAO.DAOBerita;
import java.util.Date;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;

/**
 * News generated by hbm2java
 */
@ManagedBean
public class News  implements java.io.Serializable {


     private Integer id;
     private String title;
     private String description;
     private String writer;
     private String content;
     private Date publishDate;

    public News() {
    }

    public News(String title, String description, String writer, String content, Date publishDate) {
       this.title = title;
       this.description = description;
       this.writer = writer;
       this.content = content;
       this.publishDate = publishDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getWriter() {
        return this.writer;
    }
    
    public void setWriter(String writer) {
        this.writer = writer;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getPublishDate() {
        return this.publishDate;
    }
    
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }
    
    public void save() {
        DAOBerita brt = new DAOBerita();
        brt.addBerita(this);
    }

    public void delete() {
        DAOBerita brt = new DAOBerita();
        brt.deleteBerita(id);
        title = "";
        description = "";
        writer = "";
        content = "";
    }

    public String getbyid() {
        DAOBerita brt = new DAOBerita();
        List<News> lBrt = brt.getbyID(id);
        title = lBrt.get(0).title;
        description = lBrt.get(0).description;
        writer = lBrt.get(0).writer;
        content = lBrt.get(0).content;
        return "create_news";
    }

    public List<News> getallrecords() {
        DAOBerita brt = new DAOBerita();
        List<News> lBrt = brt.retrieveNews();
        return lBrt;
    }

    public void update() {
        DAOBerita brt = new DAOBerita();
        brt.updateBerita(this);
        title = "";
        description = "";
        writer = "";
        content = "";
        FacesMessage facesMessage = new FacesMessage(FacesMessage.SEVERITY_INFO, "Sukses Mengupdate Data", null);
    }




}


